module.exports = {
    articles: {
        "1500084527": {
            item_id: "1500084527",
            resolved_id: "1500084527",
            given_url: "http://beza1e1.tuxen.de/lore/index.html",
            given_title:
                "Software Folklore – A collection of weird bug stories",
            favorite: "0",
            status: "0",
            time_added: "1588253291",
            time_updated: "1588253376",
            time_read: "0",
            time_favorited: "0",
            sort_id: 3,
            resolved_title: "Software Folklore",
            resolved_url: "http://beza1e1.tuxen.de/lore/index.html",
            excerpt:
                "Sometimes bugs have symptoms beyond belief. This is a collection of such stories from around the web. Send me more stories, if you know some.",
            is_article: "1",
            is_index: "1",
            has_video: "0",
            has_image: "0",
            word_count: "71",
            lang: "en",
            top_image_url: "http://beza1e1.tuxen.de/images/andi5.jpg",
            listen_duration_estimate: 27,
        },
        "1902191786": {
            item_id: "1902191786",
            resolved_id: "1902191786",
            given_url:
                "https://medium.com/taskworld-blog/lencionis-5-dysfunctions-of-a-team-330d58b2cd81",
            given_title:
                "Lencioni’s 5 Dysfunctions of a Team - Taskworld Blog - Medium",
            favorite: "0",
            status: "0",
            time_added: "1587343463",
            time_updated: "1588205171",
            time_read: "0",
            time_favorited: "0",
            sort_id: 7,
            resolved_title: "Lencioni’s 5 Dysfunctions of a Team",
            resolved_url:
                "https://medium.com/taskworld-blog/lencionis-5-dysfunctions-of-a-team-330d58b2cd81",
            excerpt:
                "Ahhhh, organizational politics. You can love watching Game of Thrones and the mental and physical chess battles that unfold, but it doesn’t mean you want to live them every day in your workplace. We’ve all been there. Or maybe we are there now.",
            is_article: "1",
            is_index: "0",
            has_video: "0",
            has_image: "1",
            word_count: "1335",
            lang: "en",
            time_to_read: 6,
            top_image_url:
                "https://miro.medium.com/max/1200/1*w47euUFT_ktL9iU0MOYHqg.jpeg",
            domain_metadata: [Object],
            listen_duration_estimate: 517,
        },
        "2412774056": {
            item_id: "2412774056",
            resolved_id: "2412774056",
            given_url:
                "https://www.tombartel.me/blog/exhibit-leadership-as-individual-contributor/",
            given_title:
                "How to Exhibit Leadership as an Individual Contributor",
            favorite: "0",
            status: "0",
            time_added: "1587600966",
            time_updated: "1588257571",
            time_read: "0",
            time_favorited: "0",
            sort_id: 6,
            resolved_title:
                "How to Exhibit Leadership as an Individual Contributor",
            resolved_url:
                "https://www.tombartel.me/blog/exhibit-leadership-as-individual-contributor/",
            excerpt:
                "It used to make little sense to me. Every year, when performance reviews were due, my organization evaluated everyone on several skills. Leadership was one of them.",
            is_article: "1",
            is_index: "0",
            has_video: "0",
            has_image: "1",
            word_count: "3012",
            lang: "en",
            time_to_read: 14,
            top_image_url:
                "https://www.tombartel.me/images/posts/woman-explaining-laptop.jpg",
            listen_duration_estimate: 1166,
        },
        "2682112799": {
            item_id: "2682112799",
            resolved_id: "2682112799",
            given_url:
                "https://blog.bitsrc.io/making-api-calls-with-react-hooks-748ebfc7de8c",
            given_title: "Making API Calls with React Hooks - Bits and Pieces",
            favorite: "0",
            status: "0",
            time_added: "1588964112",
            time_updated: "1589073914",
            time_read: "0",
            time_favorited: "0",
            sort_id: 1,
            resolved_title: "Making API Calls with React Hooks",
            resolved_url:
                "https://blog.bitsrc.io/making-api-calls-with-react-hooks-748ebfc7de8c",
            excerpt:
                "With the new updates coming up in the React library, it's indeed impossible to use all the new React features in your application. It’s been 6 months since the official release of React Hooks which was released with React 16.8.0 (February 6, 2019)",
            is_article: "1",
            is_index: "0",
            has_video: "0",
            has_image: "1",
            word_count: "815",
            lang: "en",
            time_to_read: 4,
            top_image_url:
                "https://miro.medium.com/max/1024/1*7fOjnGrHXIwWXvaFzz7AFA.jpeg",
            listen_duration_estimate: 315,
        },
        "2964373199": {
            item_id: "2964373199",
            resolved_id: "2964373199",
            given_url:
                "https://elements.heroku.com/buildpacks/mars/heroku-nextjs",
            given_title: "mars/heroku-nextjs - Buildpacks - Heroku Elements",
            favorite: "0",
            status: "0",
            time_added: "1588003591",
            time_updated: "1588205152",
            time_read: "0",
            time_favorited: "0",
            sort_id: 5,
            resolved_title: "mars/heroku-nextjs : Buildpacks : Heroku Elements",
            resolved_url:
                "https://elements.heroku.com/buildpacks/mars/heroku-nextjs",
            excerpt:
                "Deploy React-based universal web apps on Heroku. Once you have a Next app working locally, you may deploy it for public access.",
            is_article: "1",
            is_index: "0",
            has_video: "0",
            has_image: "0",
            word_count: "197",
            lang: "en",
            top_image_url: "https://avatars1.githubusercontent.com/u/17164?v=4",
            listen_duration_estimate: 76,
        },
        "2966344976": {
            item_id: "2966344976",
            resolved_id: "2966344976",
            given_url: "https://news.ycombinator.com/item?id=23017160",
            given_title: "Why Segment Went Back to a Monolith",
            favorite: "0",
            status: "0",
            time_added: "1588161217",
            time_updated: "1588205114",
            time_read: "0",
            time_favorited: "0",
            sort_id: 4,
            resolved_title: "Why Segment Went Back to a Monolith",
            resolved_url: "http://news.ycombinator.com/item?id=23017160",
            excerpt:
                "I think microservices work well in organizations that are big enough to have a team per microservice.",
            is_article: "1",
            is_index: "0",
            has_video: "0",
            has_image: "0",
            word_count: "4257",
            lang: "en",
            time_to_read: 19,
            domain_metadata: [Object],
            listen_duration_estimate: 1648,
        },
        "2971812438": {
            item_id: "2971812438",
            resolved_id: "2971812438",
            given_url:
                "https://www.nytimes.com/2020/05/04/health/coronavirus-office-makeover.html",
            given_title:
                "The Pandemic May Mean the End of the Open-Floor Office - The New York Times",
            favorite: "0",
            status: "0",
            time_added: "1588604312",
            time_updated: "1588635439",
            time_read: "0",
            time_favorited: "0",
            sort_id: 2,
            resolved_title:
                "The Pandemic May Mean the End of the Open-Floor Office",
            resolved_url:
                "https://www.nytimes.com/2020/05/04/health/coronavirus-office-makeover.html",
            excerpt:
                "As businesses contemplate the return of workers to their desks, many are considering large and small changes to the modern workplace culture and trappings.",
            is_article: "1",
            is_index: "0",
            has_video: "0",
            has_image: "1",
            word_count: "1381",
            lang: "en",
            time_to_read: 6,
            amp_url:
                "https://www.nytimes.com/2020/05/04/health/coronavirus-office-makeover.amp.html",
            top_image_url:
                "https://static01.nyt.com/images/2020/05/01/science/00VIRUS-WORKPLACES-promo/00VIRUS-WORKPLACES-promo-facebookJumbo.jpg",
            domain_metadata: [Object],
            listen_duration_estimate: 535,
        },
        "2978373610": {
            item_id: "2978373610",
            resolved_id: "2514879305",
            given_url: "https://link.medium.com/qvWPMsdom6",
            given_title: "“Unit Testing React Components”",
            favorite: "0",
            status: "0",
            time_added: "1589069295",
            time_updated: "1589073902",
            time_read: "0",
            time_favorited: "0",
            sort_id: 0,
            resolved_title: "Unit Testing React Components",
            resolved_url:
                "https://medium.com/javascript-scene/unit-testing-react-components-aeda9a44aae2",
            excerpt:
                "Unit testing is a great discipline which can lead to 40%-80% reductions in production bug density. Unit testing also has several other important benefits: But some things are easier to unit test than others.",
            is_article: "1",
            is_index: "0",
            has_video: "0",
            has_image: "1",
            word_count: "2813",
            lang: "en",
            time_to_read: 13,
            top_image_url:
                "https://miro.medium.com/max/1200/1*RzR_S8UJeDn0b_sEQa2V8Q.jpeg",
            domain_metadata: [Object],
            listen_duration_estimate: 1089,
        },
    },
};
